/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#001a42',
        'surface-container-highest': '#e4e2e4',
        surface: '#fcf8fa',
        'surface-tint': '#565e74',
        background: '#fcf8fa',
        'on-surface': '#1b1b1d',
        'status-draft': '#94A3B8',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f3f0f2',
        'secondary-fixed-dim': '#adc6ff',
        'surface-container-high': '#eae7e9',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-tertiary-container': '#75859d',
        'tertiary-container': '#0b1c30',
        'surface-variant': '#e4e2e4',
        'surface-dim': '#dcd9db',
        'on-primary-container': '#7c839b',
        'secondary-fixed': '#d8e2ff',
        'surface-studio': '#F8FAFC',
        'inverse-primary': '#bec6e0',
        'primary-fixed-dim': '#bec6e0',
        'surface-bright': '#fcf8fa',
        'status-review': '#F59E0B',
        'on-primary': '#ffffff',
        'surface-container': '#f0edef',
        'primary-fixed': '#dae2fd',
        'primary-container': '#131b2e',
        'ai-glow': '#DBEAFE',
        outline: '#76777d',
        'tertiary-fixed': '#d3e4fe',
        'on-primary-fixed': '#131b2e',
        'on-error-container': '#93000a',
        'on-surface-variant': '#45464d',
        'on-tertiary-fixed': '#0b1c30',
        'error-container': '#ffdad6',
        'inverse-surface': '#303032',
        'ai-vibrant': '#2563EB',
        secondary: '#0058be',
        danger: '#dc2626',
        success: '#10B981',
        warning: '#F59E0B',
        'surface-alt': '#F1F5F9',
        'muted-foreground': '#6B7280',
        'on-tertiary': '#ffffff',
        'on-background': '#1b1b1d',
        tertiary: '#000000',
        'outline-variant': '#c6c6cd',
        'status-final': '#10B981',
        'surface-container-low': '#f6f3f5',
        'secondary-container': '#2170e4',
        'on-secondary-fixed-variant': '#004395',
        primary: '#000000',
        'on-primary-fixed-variant': '#3f465c',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#38485d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'inspector-width': '320px',
        'sidebar-width': '280px',
        'margin-desktop': '32px',
        unit: '4px',
        'container-max': '1200px',
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Geist', 'sans-serif'],
        'headline-sm': ['Geist', 'sans-serif'],
        label: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      boxShadow: {
        'elevation-1': '0 1px 3px rgba(0,0,0,0.06)',
        'elevation-2': '0 4px 12px rgba(0,0,0,0.08)',
        'elevation-3': '0 8px 24px rgba(0,0,0,0.12)',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { backgroundColor: 'rgba(37, 99, 235, 0.05)' },
          '50%': { backgroundColor: 'rgba(37, 99, 235, 0.15)' },
        },
        'wave-move': {
          '0%': { backgroundPosition: '100% 0%' },
          '100%': { backgroundPosition: '-100% 0%' },
        },
        'wave-pulse': {
          '0%': { opacity: '0.4', transform: 'scaleX(0.95)' },
          '50%': { opacity: '1', transform: 'scaleX(1.05)' },
          '100%': { opacity: '0.4', transform: 'scaleX(0.95)' },
        },
      },
      animation: {
        'ai-pulse': 'pulse-glow 3s infinite ease-in-out',
        'collab-wave': 'wave-move 3s linear infinite',
        'wave-active': 'wave-pulse 2s infinite ease-in-out',
      },
    },
  },
  plugins: [],
}
